apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-java-sample
    component: deploy-to-dev
  name: deploy-to-dev
  namespace: qunliworkspace
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30861
  selector:
    app: devops-java-sample
    component: deploy-to-dev
    tier: backend
  sessionAffinity: None
  type: NodePort
