apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubesphere
    component: deploy-to-dev
  name: deploy-to-dev
  namespace: qunliworkspace
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30861
  selector:
    app: kubesphere
    component: deploy-to-dev
    tier: backend
  sessionAffinity: None
  type: NodePort
